services:
  postgres:
    container_name: my_notes
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my_notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
  postgres-data:
      